# Generated by Django 5.1.7 on 2025-04-06 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('adjusted_gross_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('haircut_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('daily_advance_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('advance_duration', models.IntegerField()),
                ('customer_name', models.CharField(max_length=20)),
                ('customer_id', models.IntegerField()),
                ('revenue_source_id', models.IntegerField()),
                ('revenue_source_name', models.CharField(max_length=30)),
                ('currency_code', models.CharField(max_length=3)),
                ('invoice_date', models.DateField()),
            ],
        ),
    ]
