# Generated by Django 5.1.7 on 2025-09-08 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
