# Generated by Django 5.1.7 on 2025-09-09 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_alter_task_metadata_alter_task_tags_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='estimated_hours',
            field=models.IntegerField(),
        ),
    ]
