name: Run Tests

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up environment
      run: |
        echo "DJANGO_PORT=8000" >> .env
        echo "DJANGO_SUPERUSER_EMAIL=admin@example.com" >> .env
        echo "DJANGO_SUPERUSER_PASSWORD=admin" >> .env
        echo "DJANGO_SUPERUSER_USERNAME=admin" >> .env
        echo "POSTGRES_DB=postgres" >> .env
        echo "POSTGRES_PASSWORD=postgres" >> .env
        echo "POSTGRES_USERNAME=postgres" >> .env
      
    - name: Run tests
      run: make test
